version: "3.9"

services:
  web:
    image: tilt.dev/otel-practice_web
    ports:
      - "8080:8080"

  jaeger:
    container_name: jaeger
    hostname: jaeger
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686" # http server (browser ui)
      - "14268:14268" # jaeger-collector http server (tracer provider)
    environment:
      LOG_LEVEL: debug
