version: "3.9"

services:
  web:
    build: .
    ports:
      - "8080:8080"

  jaeger:
    container_name: jaeger
    hostname: jaeger
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268:14268"
    environment:
      LOG_LEVEL: debug
